CITIES = [
    "Banská Bystrica",
    "Banská Štiavnica",
    "Bardejov",
    "Bratislava",
    "Brezno",
    "Bytča",
    "Bánovce nad Bebravou",
    "Čadca",
    "Detva",
    "Dolný Kubín",
    "Dunajská Streda",
    "Galanta",
    "Gelnica",
    "Hlohovec",
    "Humenné",
    "Ilava",
    "Kežmarok",
    "Komárno",
    "Košice",
    "Krupina",
    "Kysucké Nové Mesto",
    "Levice",
    "Levoča",
    "Liptovský Mikuláš",
    "Lučenec",
    "Malacky",
    "Martin",
    "Medzilaborce",
    "Michalovce",
    "Myjava",
    "Námestovo",
    "Nitra",
    "Nové Mesto nad Váhom",
    "Nové Zámky",
    "Partizánske",
    "Pezinok",
    "Piešťany",
    "Poltár",
    "Poprad",
    "Považská Bystrica",
    "Prešov",
    "Prievidza",
    "Púchov",
    "Revúca",
    "Rimavská Sobota",
    "Rožňava",
    "Ružomberok",
    "Sabinov",
    "Senec",
    "Senica",
    "Skalica",
    "Snina",
    "Sobrance",
    "Spišská Nová Ves",
    "Stará Ľubovňa",
    "Stropkov",
    "Svidník",
    "Šaľa",
    "Topoľčany",
    "Trebišov",
    "Trenčín",
    "Trnava",
    "Turčianske Teplice",
    "Tvrdošín",
    "Veľký Krtíš",
    "Vranov nad Topľou",
    "Zlaté Moravce",
    "Zvolen",
    "Žarnovica",
    "Žiar nad Hronom",
    "Žilina",
]


DISTRICTS = [
    "okres Banská Bystrica",
    "okres Banská Štiavnica",
    "okres Bardejov",
    "okres Bratislava",
    "okres Brezno",
    "okres Bytča",
    "okres Bánovce nad Bebravou",
    "okres Čadca",
    "okres Detva",
    "okres Dolný Kubín",
    "okres Dunajská Streda",
    "okres Galanta",
    "okres Gelnica",
    "okres Hlohovec",
    "okres Humenné",
    "okres Ilava",
    "okres Kežmarok",
    "okres Komárno",
    "okres Košice",
    "okres Krupina",
    "okres Kysucké Nové Mesto",
    "okres Levice",
    "okres Levoča",
    "okres Liptovský Mikuláš",
    "okres Lučenec",
    "okres Malacky",
    "okres Martin",
    "okres Medzilaborce",
    "okres Michalovce",
    "okres Myjava",
    "okres Námestovo",
    "okres Nitra",
    "okres Nové Mesto nad Váhom",
    "okres Nové Zámky",
    "okres Partizánske",
    "okres Pezinok",
    "okres Piešťany",
    "okres Poltár",
    "okres Poprad",
    "okres Považská Bystrica",
    "okres Prešov",
    "okres Prievidza",
    "okres Púchov",
    "okres Revúca",
    "okres Rimavská Sobota",
    "okres Rožňava",
    "okres Ružomberok",
    "okres Sabinov",
    "okres Senec",
    "okres Senica",
    "okres Skalica",
    "okres Snina",
    "okres Sobrance",
    "okres Spišská Nová Ves",
    "okres Stará Ľubovňa",
    "okres Stropkov",
    "okres Svidník",
    "okres Šaľa",
    "okres Topoľčany",
    "okres Trebišov",
    "okres Trenčín",
    "okres Trnava",
    "okres Turčianske Teplice",
    "okres Tvrdošín",
    "okres Veľký Krtíš",
    "okres Vranov nad Topľou",
    "okres Zlaté Moravce",
    "okres Zvolen",
    "okres Žarnovica",
    "okres Žiar nad Hronom",
    "okres Žilina",
    ]

RE_TYPES = [
    "Garsónka",
    "Dvojgarsónka",
    "1 izbový byt",
    "2 izbový byt",
    "3 izbový byt",
    "4 izbový byt",
    "5 a viac izbový byt",
    "Mezonet",
    "Apartmán",
    "Loft",
    "Iný byt",

    "Rodinný dom",
    "Rodinná vila",
    "Zrubový dom",
    "Bungalov",
    "Vidiecky dom",
    "Bývalá poľnohosp. usadlosť",
    "Mobilný dom",
    "Hausbót",
    "Iný objekt na bývanie",

    "Chata, drevenica, zrub",
    "Chalupa, rekreačný domček",
    "Záhradná chatka",
    "Iný objekt na rekreáciu",

    "Garáž",
    "Hotel, penzión",
    "Objekt pre obchod",
    "Reštaurácia",
    "Skladový objekt",
    "Polyfunkčný objekt",
    "Administratívny objekt",
    "Výrobný objekt",
    "Historický objekt",
    "Nájomný dom",
    "Prevádzkový areál",
    "Poľnohosp. objekt",
    "Bytový dom",
    "Apartmánový dom",
    "Spevnené plochy",
    "Objekt pre šport",
    "Opravárenský objekt",
    "Kúpeľný objekt",
    "Čerpacia stanica PHM",
    "Malá elektráreň",
    "Mobilné bunky a stánky",
    "Iný komerčný objekt",
    "Iný prevádzkový objekt",
    "Iný objekt",

    "Kancelárie, admin. priestory",
    "Obchodné priestory",
    "Reštauračné priestory",
    "Skladové priestory",
    "Výrobné priestory",
    "Športové priestory",
    "Opravárenské priestory",
    "Plocha pre reklamu",
    "Iné komerčné priestory",
    "Iné prevádzkové priestory",

    "Pozemok pre rod. domy",
    "Rekreačný pozemok",
    "Pozemok pre bytovú výstavbu",
    "Orná pôda",
    "Záhrada",
    "Priemyselná zóna",
    "Komerčná zóna",
    "Pozemok pre obč. vybavenosť",
    "Zmiešaná zóna",
    "Lesy",
    "Rybník, vodná plocha",
    "Lúka, pasienok",
    "Chmelnica, vinica",
    "Sad",
    "Pozemok pre reklamu",
    "Iný stavebný pozemok",
    "Iný poľnohosp. pozemok",
]
